### ISSUE TITLE
<Box.Header.UserBlock> component

### ISSUE THREAD

**Issue by jonmpqts** [jonmpqts/react-admin-lte#3]
As seen on the [widgets page](https://almsaeedstudio.com/themes/AdminLTE/pages/widgets.html)

<img width="794" alt="screen shot 2016-08-10 at 9 51 14 am" src="https://cloud.githubusercontent.com/assets/145313/17562545/320cb9c2-5ee0-11e6-8e1a-2d6c56c1dae8.png">

A box header can have a `<div class="user-block">` added to it that renders instead of the title. Adding this will require the `title` on `<Box.Header>` is made optional.

**Comment by KorySchneider** [comment]
Done in https://github.com/jonmpqts/react-admin-lte/commit/e64aa5ab06550f6bb3619423c690ae3fa6528039
