### ISSUE TITLE
<MainHeader> components

### ISSUE THREAD

**Issue by jonmpqts** [jonmpqts/react-admin-lte#4]
`<MainHeader>` is the main wrapper for the bar at the top:

<img width="1240" alt="screen shot 2016-08-10 at 9 57 58 am" src="https://cloud.githubusercontent.com/assets/145313/17562731/f3613832-5ee0-11e6-94bd-ee1bc5e712f4.png">

It accepts children and wraps them in a `<header className="main-header">`.

`MainHeader.Logo` renders as `<a class="logo">` and has three properties:

- `href` this will be the href that is set on `<a>`
- `mini` this will be used as the logo when the screen size is small and should be wrapped in `<span class="logo-mini">` which will be placed as a child within `<a>`
- `large` this will be used as the normal logo and should be wrapped in `<span class="logo-large">` which will also be placed as a child within `<a>`

**Comment by KorySchneider** [comment]
Added `MainHeader` in https://github.com/jonmpqts/react-admin-lte/commit/6580e950f5d3ae236e1d95b45779cd5b2de5aabe and `MainHeaderLogo` in https://github.com/jonmpqts/react-admin-lte/commit/ce0ac8002f6cc7134e789413b2071540235f384c

**Comment by jonmpqts** [comment]
Added in 7235cd6434140cd02fb9995fb6105d18cac11bf3.
