### ISSUE TITLE
<Sidebar> components

### ISSUE THREAD

**Issue by jonmpqts** [jonmpqts/react-admin-lte#5]
- `<Sidebar>` is the wrapper for the sidebar:

<img width="231" alt="screen shot 2016-08-10 at 10 04 28 am" src="https://cloud.githubusercontent.com/assets/145313/17562941/f7bddcae-5ee1-11e6-83b7-7d4a3ee15d8b.png">

It should accept children and render them inside `<aside class="main-sidebar"><section class="sidebar">`.

- `<Sidebar.Toggle>` is the toggle for the sidebar that is placed in the `<MainHeader><Nav>`:

<img width="70" alt="screen shot 2016-08-10 at 10 08 28 am" src="https://cloud.githubusercontent.com/assets/145313/17563050/6a3c9ca2-5ee2-11e6-8970-e1a645f934c5.png">

It should render as

```
<a href="#" class="sidebar-toggle">
  <span class="sr-only">{srText}</span>
  <span class="icon-bar" />
  <span class="icon-bar" />
  <span class="icon-bar" />
</a>
```

where `srText` is a property accepting text to show to a screen reader.

`<Sidebar.UserPanel>` is the upper part of the sidebar:

<img width="229" alt="screen shot 2016-08-10 at 10 17 23 am" src="https://cloud.githubusercontent.com/assets/145313/17563319/b4a9f248-5ee3-11e6-9a2a-a4bf481536bb.png">

It accepts children and renders them inside `<div class="user-panel">`.

`<Sidebar.UserPanel.Image>` accepts children and renders them inside `<div class="pull-left image">`

`<Sidebar.UserPanel.Info>`accepts children and renders them inside `<div class="pull-left info">`

`<Sidebar.Menu>` is a wrapper for the menu in the sidebar. It accepts children and renders them inside `<ul class="sidebar-menu">`.

`<Sidebar.Menu.Header>` represents an header for a list of items in the menu. It accepts a `title` property and renders it inside `<li class="header">`.

`<Sidebar.Menu.Item>` accepts children and renders them inside of `<li>`. It also accepts an `active` bool property with a default of `false` that sets a class of the same name on the `<li>`.

**Comment by KorySchneider** [comment]
Done in https://github.com/jonmpqts/react-admin-lte/commit/b7cf4056865d4a21752e947928e9759696b934d3
